# For secret informations :) #
DATABASE:
  ADDRESS:
  NAME:
  USER:
  PASSWORD:
domain-name: noks.io
send-join-and-quit-message-to-op: true
# \n for newLine
tab:
  header: "Noks.io"
  footer: "github.com/iamnoksio/KitPvPSoup"
motd:
  first-line: "noks.io"
  second-line: "soup server"
welcome-message:
  - "&8&m-------------------------------------------------"
  - "&3| &rWelcome on the BETA phase of &3&lSoupWorld &rthe home of soup pvp!"
  - " "
  - "&3| &rOur Website >> &cComing Soon"
  - "&3| &rOur Discord >> &3discord.soupworld.net"
  - "&c-> Keep in mind this is a beta ^^"
  - "&cIf you encounter a bug, report it on the discord ^^"
  - "&8&m-------------------------------------------------"
# Setup KOTH Locations with names you can also use /koth setup <KOTH NAME>
KoTH:
  NAME:
    LOCATION: 
  NAME2:
    LOCATION: 