main: io.noks.kitpvp.Main
name: KitPvPSoup
version: 1.5
author: Noksio
website: github.com/iamnoksio/KitPvP-Soup
commands:
  abilitylist:
  ping:
    aliases: [ms]
  shout:
  report:
  skull:
  sponsor:
  stats:
  build:
  boot:
    aliases: [ddos]
  balance:
    aliases: [money, bal]
  pay:
  feast:
  spawn:
  repair:
  shop:
  discord:
  guild:
    aliases: [clan, teams, team, clans, guilds, g]
  bounty: